#!/usr/bin/env ruby

require "bundler/setup"

require "dry/cli"

require "jfm"

module Jfm
  module CLI
    class Command < Dry::CLI::Command
      def self.inherited(klass)
        super

        klass.option :dir, aliases: ["-d"], default: ".", desc: "Path to your Jekyll directory. Assumes the current directory."
      end
    end

    module Commands
      extend Dry::CLI::Registry

      class Version < Jfm::CLI::Command
        desc "Print version"

        def call(*)
          puts Jfm::VERSION
        end
      end

      class Find < Jfm::CLI::Command
        desc "Search for files with specific frontmatter. Outputs a list of filenames."

        argument :queries, type: :array, required: true, desc: "Query/queries to match"

        example [
          %q("layout"         # Finds all posts that have a "layout" value set in their frontmatter),
          %q("layout: post"   # Finds all posts whose "layout" value is set to "post"),
          %q("layout: ~post"  # Finds all posts whose "layout" value is *not* set to "post")
        ]

        def call(dir:, queries: [], **)
          site = Site.new(dir)

          posts = site.posts.select do |post|
            queries.all? { |q| post.match?(q) }
          end

          posts.each do |post|
            puts post.filename
          end
        end
      end

      register "version", Version, aliases: ["v", "-v", "--version"]
      register "find",    Find,    aliases: ["f"]
    end
  end
end

Dry::CLI.new(Jfm::CLI::Commands).call
